### ISSUE TITLE
🐛[BUG][Combat] Carbuncle's Pole seems to add Dragon Affinity? (Possibly others)

### ISSUE THREAD

**Issue by Clonegoat** [HorizonFFXI/HorizonXI-Issues#1710]
**What does this bug affect?**
Carbuncle's Pole seems to have a Dragon Affinity hidden effect to it (that I cannot find any evidence of anywhere to support it being accurate)

**Steps to Reproduce**
While farming Brook Sahagin (DRG) today for a Mermaid's Head, I noticed a decent amount of Intimidations on my SMN/THF. I was struggling to work out what piece of gear was possibly causing this, and when I swapped back to Apollo's Staff it stopped entirely.

**Expected behavior**
As far as I can find anywhere on the internet, Carbuncle's Pole shouldn't have any "Affinity" effects attached to it. I want to go test if it has any others, namely Arcana/Demon/Undead but have not yet

**Screenshots**
![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/80860333/32cde783-9921-4aae-a37f-36c51bce9c7f)
Screenshot shows 2 Intimidates and my current gear which as far as I'm aware nothing should have Dragon Affinity attached to it

**Setup Information**
/ver 30221103_1

**Additional context**
Gear: Carbuncle's Pole, Hedgehog Bomb, Vermillion Cloak, Peacock Amulet, Beaslty Earring, Magnetic Earring, Carbuncle's Mitts, Tamas Ting, Evoker's Ring, Summoner's Cape, Swift Belt, Evoker's Spats, Evoker's Pigaches +1

**Comment by lapislosh** [comment]
It seems like this was fixed with https://github.com/AirSkyBoat/AirSkyBoat/pull/3078 but then reverted here https://github.com/AirSkyBoat/AirSkyBoat/pull/3173
1180 does seems like the correct value according to the enums, but if 1178 is required for the item to actually function... well I have no idea.

**Comment by Clonegoat** [comment]
Funnily enough, it still doesn't function as a use item either. I know that was reported elsewhere, not sure if it was closed or not

**Comment by Clonegoat** [comment]
I have recently discovered the latent also works with any avatar summoned, not just carbuncle
