### ISSUE TITLE
🐛[BUG][System] Level sync equipment scaling

### ISSUE THREAD

**Issue by RetroPrez** [HorizonFFXI/HorizonXI-Issues#355]
**What does this bug affect?**
Level sync currently has equipment scaling enabled.

**Expected behavior**
Previously any gear higher than the area sync would be unequipped and unavailable.

![Retroprez_2022 11 01_021231](https://user-images.githubusercontent.com/112651690/199170547-96f2e9c1-e260-4596-8552-328c969ed991.png)

**Comment by The-Aerec** [comment]
fixed on server restart

**Comment by Squinkerdoodle** [comment]
@The-Aerec  this issue is still occurring.
![image](https://user-images.githubusercontent.com/112344508/199372076-26edfd54-4568-474f-8139-51f589854cce.png)

**Comment by OpheliaXI** [comment]
Verified working on ASB.

**Comment by OpheliaXI** [comment]
Verified working on Horizon local.

**Comment by Squinkerdoodle** [comment]
Yup good to close again!
