### ISSUE TITLE
🐛[BUG][System/Combat] Maat Fight

### ISSUE THREAD

**Issue by bigggele** [HorizonFFXI/HorizonXI-Issues#809]
**What does this bug affect?**
The Maat fight is currently incorrect and it's allowing you to have a subjob, It seems to activate the subjob after being in the bcnm for over a minute.

**Expected behavior**
You should have no subjob while in the Maat fight.

**Screenshots**
![maat1](https://user-images.githubusercontent.com/121577008/211969923-fe44fcb8-373f-4d34-9300-6056d5aefac7.png)
![maat2](https://user-images.githubusercontent.com/121577008/211969932-12c7c1a5-edf8-48b1-afef-89cb1ec861d9.png)
![maat](https://user-images.githubusercontent.com/121577008/211969996-578eeb18-f80e-4325-af9f-bcaf03b4da0c.PNG)

**Comment by TaodR** [comment]
I have experienced the same phenomenon, it seems very bizarre that not a single person but biggggggggele has reported this abusable bug on this 4k+ server.
![image](https://user-images.githubusercontent.com/8005954/212199975-658e5c90-85c0-4de8-80a5-5413af1f2885.png)

**Comment by dallano** [comment]
This was fixed. And is linked in an overarching issue elsewhere. Thank you for the report!

**Comment by Luaithel** [comment]
This is not fixed, it just happened to me as well.
![Maat fight](https://user-images.githubusercontent.com/121269267/213319117-36dbee25-5d38-4a0f-9745-2a1709011476.jpg)

**Comment by dallano** [comment]
It's just not on live yet
