### ISSUE TITLE
🐛[BUG]SMN AF body adding bloodpact delay instead of reducing it

### ISSUE THREAD

**Issue by XIBrixy** [HorizonFFXI/HorizonXI-Issues#874]
**What does this bug affect?**
Evoker's Doublet is adding 1 second to bloodpact recast instead of reducing the delay by 1 second.

**Steps to Reproduce**
Use any Bloodpact

**Expected behavior**
Should reduce delay. Increases it instead

**Screenshots**
https://imgur.com/a/MTmz5p2

**Additional context**
Coding is backwards. Very simple to fix.

**Comment by TracentEden** [comment]
This is being fixed by incoming PR (watch patch notes).

**Comment by XIBrixy** [comment]
It's been 2 weeks now since it was marked as fixed. Issue is still here.

**Comment by TracentEden** [comment]
> It's been 2 weeks now since it was marked as fixed. Issue is still here.

There is a delay between the fix getting merged and deployed onto the live server. Watch the patch notes to see when it is added to live server.
